### ISSUE TITLE
Curious if you checked out DAGsHub

### ISSUE THREAD

**Issue by deanp70** [lucmos/nn-template#6]
Hi @lucmos, this looks like an awesome repo. I stumbled on it while doing some research on project templates for ML projects. I'm one of the creators of [DAGsHub](https://DAGsHub.com) which is a platform built on Git, DVC, and MLflow. It integrates with GitHub and provides a free DVC remote and MLflow server so that you can track experiments and share your data & models in one UI.

Here's an example project to showcase the abilities:
https://dagshub.com/OperationSavta/SavtaDepth

It seems really in line with what you're creating here, and I would love to hear your thoughts about it.

**Comment by Flegyas** [comment]
I'm sorry for the late reply. It's been a month of deadlines for both of us!

Regarding DAGsHub, we find it really interesting and definitely worth trying. The issue we, personally, have is that we usually work with very huge (and sometimes proprietary) datasets. While it is easy to handle them locally, it might be problematic with the upload and the account storage limit. 

Regarding its MLFlow integration, I must say that it is really appealing, but we switched from MLFlow to WandB years ago for its richer set of features. If we ever switch back to MLFlow, we'll definitely add DAGsHub to our toolbox too.

For the moment, we'll stick with the raw DVC, but we'll consider mentioning your tool in the README since it could be useful for many users!

**Comment by deanp70** [comment]
Hey @Flegyas, thanks for responding, I appreciate it. A few notes/questions I have are:
1. Do you mean your data is stored only locally and isn't shared with other team members?
    * If so, I understand, in that case, the only advantage of connecting to DAGsHub is you'll be able to see your DVC pipeline, but as I understand, you're not using one, so that it won't make too much sense.
    * If you are storing it on S3 or Google Storage, you can actually connect your external storage to DAGsHub, which means you'll have all the existing features, "infinite" storage, and you don't need to move your data anywhere. That way you can visualize and diff data if that's helpful to you.
2. If you feel like it, I'd love to know what the killer features for you with WandB (over MLflow) are? Is it that the UI is nicer overall, or do you have something specific you like?

Overall, I would really love to appear in the README, with the hope it will help anyone. I can create a PR for it if you think that makes sense.

Thanks again!

**Comment by lucmos** [comment]
Hello!

I didn't know about the possibility of "infinity" storage on DAGsHub; that is for sure a strong plus!

Another problem that I faced when I wanted to try it is the following:

> Private repos are currently free with up to 2 additional collaborators. 

The current workflow in my research group is to develop/experiment in private repositories and then publish the code when it 
is ready. If we adopt DAGsHub, we can only have 3 collaborators, if I did not misunderstand.

One final limitation that I see in adopting DAGsHub is that currently it is cloud-only. Sometimes we deal with data/projects under strict NDA which can not be uploaded to cloud services. (in these cases, we use wandb on premise)

Regarding WandB vs. MLflow, it has been some years since I tried MLflow, thus, my comments may be outdated. 
The first thing that catches the eye is for sure the UI. It is graphically nicer and enables dynamic experiments analysis, in particular the ability to add plots/filters to decide how to visualize things *after* you logged everything you could. Another cool feature that we use is the "report", i.e. markdown files where you can embed plots dynamically (instead of screenshots).
It is not perfect though, lately it feels the UI became slower to load.

Finally, we currently do not exploit all the functionalities of DVC, and use it only to perform data versioning. Can DAGsHub 
be useful anyway in this scenario?

**Comment by deanp70** [comment]
@lucmos, Very cool! thanks for the detailed response.
The limitation on private repositories can be expanded of course, but that is part of the paid offering ([found here](https://dagshub.com/plans)). On-prem installation is also possible as mentioned. The main goal of the current structure is you can try out all DAGsHub capabilities for free to make sure it suits your workflow, and then decide if you want to take the plunge :)

Regarding MLflow vs WandB, thanks, it's really informative. The customizability of WandB charts and reports functionality are things we're thinking a lot about and working to improve.

Regarding DVC, I think DAGsHub shines mostly in the versioning part of DVC. we also show your DVC pipeline, but the main capabilities you'd be receiving is viewing your DVC cache in a human-readable way, easier sharing (and therefore reproducibility), and the ability to diff data (tables, images, MRI data, etc..) as well as notebook diffing. Also, we're always looking for the next thing we should work on, so if you have any requests or feedback I'd love to hear it.
